# [START django_app]
runtime: python38


entrypoint: gunicorn -b :$PORT elElectricistaProject.wsgi

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static_in_env/


# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
# [END django_app]

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
  SQL_INSTANCE_HOST : '/cloudsql/elelectricista:us-central1:elelectricista'
  DATABASE_NAME : 'elelectricista'
  DATABASE_USER : 'elelectricista'
  DATABASE_ENGINE: 'django.db.backends.mysql'
  PROJECT_SECRET_MANAGER_ID: '192250245556'
  SECRET_DATABASE_PASSWORD_ID: 'DataBasePassword'
  SECRET_PDFCROWD_PASSWORD_ID: 'PdfCrowdPassword'
  GMAIL_APP_PASSWORD_ID: 'GmailAppPassword'

